from typing import Any, Dict, List, Optional, Literal, Tuple

from pydantic import BaseModel, Field, ValidationError

from utils import chunk_text

RiskLevel = Literal["low", "medium", "high"]


class Issue(BaseModel):
    file: str
    line: Optional[int] = None
    issue: str
    fix: Optional[str] = None


class TestSuggestion(BaseModel):
    package: Optional[str] = None
    test_name: str
    reason: str


class ReviewOutput(BaseModel):
    summary: str
    risk_level: RiskLevel
    blocking_issues: List[Issue] = Field(default_factory=list)
    non_blocking: List[Issue] = Field(default_factory=list)
    tests_to_add: List[TestSuggestion] = Field(default_factory=list)


def build_file_context(
    pr_files: List[Dict[str, Any]],
    patch_chunk_chars: int = 3500,
    max_total_chunks: int = 80,
) -> Tuple[List[Dict[str, Any]], List[str]]:
    """
    Create compact file summaries (with patch chunks), and allowed_files list.
    """
    allowed_files = [f.get("filename") for f in pr_files if f.get("filename")]
    file_summaries: List[Dict[str, Any]] = []

    chunk_count = 0
    for f in pr_files:
        filename = f.get("filename")
        if not filename:
            continue

        patch = f.get("patch")  # can be None for large diffs
        patch_chunks: List[str] = []
        if patch:
            for c in chunk_text(patch, patch_chunk_chars):
                if chunk_count >= max_total_chunks:
                    break
                patch_chunks.append(c)
                chunk_count += 1

        file_summaries.append(
            {
                "filename": filename,
                "status": f.get("status"),
                "additions": f.get("additions"),
                "deletions": f.get("deletions"),
                "changes": f.get("changes"),
                "patch_missing": patch is None,
                "patch_chunks": patch_chunks,
            }
        )

        if chunk_count >= max_total_chunks:
            break

    return file_summaries, allowed_files


def validate_review_against_allowed_files(review: ReviewOutput, allowed_files: List[str]) -> None:
    for bucket in (review.blocking_issues, review.non_blocking):
        for it in bucket:
            if it.file not in allowed_files:
                raise RuntimeError(f"Guardrail: model referenced file not in PR: {it.file}")


def format_review(review: ReviewOutput) -> str:
    lines: List[str] = []
    lines.append("## 🤖 DevAgent PR Review")
    lines.append("")
    lines.append(f"**Risk:** {review.risk_level.upper()}")
    lines.append("")
    lines.append(f"**Summary:** {review.summary}")
    lines.append("")

    if review.blocking_issues:
        lines.append("### 🚫 Blocking issues")
        for i, it in enumerate(review.blocking_issues, 1):
            loc = f"{it.file}" + (f":{it.line}" if it.line else "")
            lines.append(f"{i}. **{loc}** — {it.issue}")
            if it.fix:
                lines.append(f"   - Fix: {it.fix}")
        lines.append("")

    if review.non_blocking:
        lines.append("### ✅ Non-blocking improvements")
        for i, it in enumerate(review.non_blocking, 1):
            loc = f"{it.file}" + (f":{it.line}" if it.line else "")
            lines.append(f"{i}. **{loc}** — {it.issue}")
            if it.fix:
                lines.append(f"   - Suggestion: {it.fix}")
        lines.append("")

    if review.tests_to_add:
        lines.append("### 🧪 Tests to add")
        for i, t in enumerate(review.tests_to_add, 1):
            pkg = f" ({t.package})" if t.package else ""
            lines.append(f"{i}. **{t.test_name}**{pkg} — {t.reason}")
        lines.append("")

    lines.append("_Generated by DevAgent CLI_")
    return "\n".join(lines)
